"""Configuration templates for ChronoClean."""

MINIMAL_CONFIG = '''\
# ChronoClean configuration
# Generated by: chronoclean config init
# Documentation: https://github.com/ChronoClean/chronoclean/blob/main/docs/CONFIGURATION.md

sorting:
  folder_structure: "YYYY/MM"  # Options: YYYY, YYYY/MM, YYYY/MM/DD

# Uncomment to enable features:

# folder_tags:
#   enabled: true
#   ignore_list: ["tosort", "misc", "temp", "backup"]

# renaming:
#   enabled: true
#   pattern: "{date}_{time}"
'''

FULL_CONFIG = '''\
# ChronoClean configuration
# Generated by: chronoclean config init --full
# Documentation: https://github.com/ChronoClean/chronoclean/blob/main/docs/CONFIGURATION.md
#
# CLI arguments always override config file values.

version: "1.0"

# ============================================================================
# GENERAL SETTINGS
# ============================================================================
general:
  timezone: "local"           # Timezone for date operations
  recursive: true             # Scan subdirectories
  include_videos: true        # Include video files in scans
  ignore_hidden_files: true   # Skip files/folders starting with '.'
  dry_run_default: true       # Default to dry-run mode (safe)
  output_folder: ".chronoclean"

# ============================================================================
# SCAN SETTINGS
# ============================================================================
scan:
  image_extensions:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
    - ".tif"
    - ".heic"
    - ".heif"
    - ".webp"
    - ".bmp"
    - ".gif"
  video_extensions:
    - ".mp4"
    - ".mov"
    - ".avi"
    - ".mkv"
    - ".m4v"
    - ".3gp"
    - ".wmv"
    - ".webm"
  raw_extensions:
    - ".cr2"
    - ".nef"
    - ".arw"
    - ".dng"
    - ".orf"
    - ".rw2"
  skip_exif_errors: true
  limit: null                 # Set to integer for debugging (e.g., 100)

# ============================================================================
# SORTING SETTINGS
# ============================================================================
sorting:
  folder_structure: "YYYY/MM" # Options: YYYY, YYYY/MM, YYYY/MM/DD
  fallback_date_priority:     # Order to try when inferring dates
    - "exif"                  # EXIF metadata (most reliable)
    - "filesystem"            # File modification date
    - "folder_name"           # Date parsed from folder name

# ============================================================================
# FOLDER TAGS
# Detect meaningful folder names and optionally add them to filenames
# ============================================================================
folder_tags:
  enabled: false              # Enable folder tag detection
  min_length: 3               # Minimum tag length
  max_length: 40              # Maximum tag length
  ignore_list:                # Folder names to never use as tags
    - "tosort"
    - "unsorted"
    - "misc"
    - "backup"
    - "temp"
    - "tmp"
    - "download"
    - "downloads"
    - "dcim"
    - "camera"
    - "pictures"
    - "photos"
    - "images"
  force_list: []              # Always use these as tags (overrides ignore)
  distance_threshold: 0.75    # Fuzzy match threshold (0.0-1.0)

# ============================================================================
# FILE RENAMING
# ============================================================================
renaming:
  enabled: false              # Enable file renaming
  pattern: "{date}_{time}"    # Rename pattern
  date_format: "%Y%m%d"       # strftime format for {date}
  time_format: "%H%M%S"       # strftime format for {time}
  tag_part_format: "_{tag}"   # Format when adding folder tag
  lowercase_extensions: true  # Convert .JPG to .jpg

# ============================================================================
# DUPLICATE HANDLING
# ============================================================================
duplicates:
  policy: "safe"              # safe, skip, overwrite
  hashing_algorithm: "sha256" # sha256, md5

# ============================================================================
# LOGGING
# ============================================================================
logging:
  level: "info"               # debug, info, warning, error
  color_output: true          # Colored terminal output
  log_to_file: true           # Write to log file
  file_path: ".chronoclean/chronoclean.log"

# ============================================================================
# PERFORMANCE (for large libraries)
# ============================================================================
performance:
  multiprocessing: true       # Use multiple CPU cores
  max_workers: 0              # 0 = auto-detect
  chunk_size: 500             # Files per batch

# ============================================================================
# SYNOLOGY NAS SETTINGS
# ============================================================================
synology:
  safe_fs_mode: true          # Extra filesystem safety checks
  min_free_space_mb: 500      # Minimum free space required (MB)
'''


def get_config_template(full: bool = False) -> str:
    """Get configuration template content.
    
    Args:
        full: If True, return full config with all options.
              If False, return minimal config.
    
    Returns:
        Configuration template as string.
    """
    return FULL_CONFIG if full else MINIMAL_CONFIG
