"""Configuration templates for ChronoClean."""

MINIMAL_CONFIG = '''\
# ChronoClean configuration
# Generated by: chronoclean config init
# Documentation: https://github.com/ChronoClean/chronoclean/blob/main/docs/CONFIGURATION.md

sorting:
  folder_structure: "YYYY/MM"  # Options: YYYY, YYYY/MM, YYYY/MM/DD

# Uncomment to enable features:

# folder_tags:
#   enabled: true
#   ignore_list: ["tosort", "misc", "temp", "backup"]

# renaming:
#   enabled: true
#   pattern: "{date}_{time}"

# video_metadata:
#   enabled: true              # Extract dates from video files (v0.3)
#   providers: ["ffprobe", "hachoir"]

# filename_date:
#   enabled: true              # Extract dates from filenames (v0.2)
#   priority: "after_exif"     # before_exif, after_exif, after_filesystem

# date_mismatch:
#   enabled: true              # Detect date mismatches (v0.2)
#   threshold_days: 1

# duplicates:
#   on_collision: "check_hash" # check_hash, rename, skip, fail
'''

FULL_CONFIG = '''\
# ChronoClean configuration
# Generated by: chronoclean config init --full
# Documentation: https://github.com/ChronoClean/chronoclean/blob/main/docs/CONFIGURATION.md
#
# CLI arguments always override config file values.

version: "1.0"

# ============================================================================
# GENERAL SETTINGS
# ============================================================================
general:
  timezone: "local"           # Timezone for date operations
  recursive: true             # Scan subdirectories
  include_videos: true        # Include video files in scans
  ignore_hidden_files: true   # Skip files/folders starting with '.'
  dry_run_default: true       # Default to dry-run mode (safe)
  output_folder: ".chronoclean"

# ============================================================================
# SCAN SETTINGS
# ============================================================================
scan:
  image_extensions:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
    - ".tif"
    - ".heic"
    - ".heif"
    - ".webp"
    - ".bmp"
    - ".gif"
  video_extensions:
    - ".mp4"
    - ".mov"
    - ".avi"
    - ".mkv"
    - ".m4v"
    - ".3gp"
    - ".wmv"
    - ".webm"
  raw_extensions:
    - ".cr2"
    - ".nef"
    - ".arw"
    - ".dng"
    - ".orf"
    - ".rw2"
  skip_exif_errors: true
  limit: null                 # Set to integer for debugging (e.g., 100)

# ============================================================================
# SORTING SETTINGS
# ============================================================================
sorting:
  folder_structure: "YYYY/MM" # Options: YYYY, YYYY/MM, YYYY/MM/DD
  fallback_date_priority:     # Order to try when inferring dates
    - "exif"                  # EXIF metadata (most reliable for images)
    - "video_metadata"        # Video container metadata (v0.3)
    - "filename"              # Date parsed from filename
    - "filesystem"            # File modification date
    - "folder_name"           # Date parsed from folder name

# ============================================================================
# FOLDER TAGS
# Detect meaningful folder names and optionally add them to filenames
# ============================================================================
folder_tags:
  enabled: false              # Enable folder tag detection
  min_length: 3               # Minimum tag length
  max_length: 40              # Maximum tag length
  ignore_list:                # Folder names to never use as tags
    - "tosort"
    - "unsorted"
    - "misc"
    - "backup"
    - "temp"
    - "tmp"
    - "download"
    - "downloads"
    - "dcim"
    - "camera"
    - "pictures"
    - "photos"
    - "images"
  force_list: []              # Always use these as tags (overrides ignore)
  distance_threshold: 0.75    # Fuzzy match threshold (0.0-1.0)

# ============================================================================
# FILE RENAMING
# ============================================================================
renaming:
  enabled: false              # Enable file renaming
  pattern: "{date}_{time}"    # Rename pattern
  date_format: "%Y%m%d"       # strftime format for {date}
  time_format: "%H%M%S"       # strftime format for {time}
  tag_part_format: "_{tag}"   # Format when adding folder tag
  lowercase_extensions: true  # Convert .JPG to .jpg

# ============================================================================
# DUPLICATE HANDLING
# ============================================================================
duplicates:
  enabled: true               # Enable duplicate detection on collision
  policy: "safe"              # Planned: safe, skip, overwrite
  hashing_algorithm: "sha256" # sha256, md5
  on_collision: "check_hash"  # check_hash, rename, skip, fail

# ============================================================================
# VIDEO METADATA SETTINGS (v0.3)
# Extract creation dates from video container metadata
# ============================================================================
video_metadata:
  enabled: true               # Enable video metadata extraction
  providers:                  # Extraction methods in priority order
    - "ffprobe"               # Fast & accurate (requires ffprobe)
    - "hachoir"               # Pure Python fallback (always available)

# ============================================================================
# FILENAME DATE PARSING (v0.2)
# Extract dates from filenames like IMG_20240315_143000.jpg
# ============================================================================
filename_date:
  enabled: true               # Enable filename date extraction
  # patterns: []              # Planned: custom patterns (uses built-in)
  year_cutoff: 30             # 2-digit year: 00-30 = 2000s, 31-99 = 1900s
  priority: "after_exif"      # before_exif, after_exif, after_filesystem

# ============================================================================
# DATE MISMATCH DETECTION (v0.2)
# Flag files where filename date differs from EXIF/filesystem date
# ============================================================================
date_mismatch:
  enabled: true               # Enable mismatch detection
  threshold_days: 1           # Days difference to flag as mismatch
  # warn_on_scan: true        # Planned: show warnings during scan
  # include_in_export: true   # Planned: conditionally include in export

# ============================================================================
# EXPORT SETTINGS (v0.2)
# ============================================================================
export:
  default_format: "json"      # json, csv
  include_statistics: true    # Include summary stats in export
  # include_folder_tags: true # Planned: include folder tag fields
  pretty_print: true          # Format JSON with indentation
  output_path: ".chronoclean/export"

# ============================================================================
# LOGGING
# ============================================================================
logging:
  level: "info"               # debug, info, warning, error
  color_output: true          # Colored terminal output
  log_to_file: true           # Write to log file
  file_path: ".chronoclean/chronoclean.log"

# ============================================================================
# PERFORMANCE (for large libraries)
# ============================================================================
performance:
  multiprocessing: true       # Use multiple CPU cores
  max_workers: 0              # 0 = auto-detect
  chunk_size: 500             # Files per batch

# ============================================================================
# SYNOLOGY NAS SETTINGS
# ============================================================================
synology:
  safe_fs_mode: true          # Extra filesystem safety checks
  min_free_space_mb: 500      # Minimum free space required (MB)
'''


def get_config_template(full: bool = False) -> str:
    """Get configuration template content.
    
    Args:
        full: If True, return full config with all options.
              If False, return minimal config.
    
    Returns:
        Configuration template as string.
    """
    return FULL_CONFIG if full else MINIMAL_CONFIG
